Exception in thread Thread-1 (_start_bomb_window):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/spartans/Downloads/Bomb-Project-main/bomb.py", line 15, in _start_bomb_window
    gui2 = BombGUI (
           ^^^^^^^^^
  File "/home/spartans/Downloads/Bomb-Project-main/bomb_gui.py", line 39, in __init__
    self.photo_label = ttk.Label(self, image=self.photo_closed)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tkinter/ttk.py", line 729, in __init__
    Widget.__init__(self, master, "ttk::label", kw)
  File "/usr/lib/python3.11/tkinter/ttk.py", line 527, in __init__
    tkinter.Widget.__init__(self, master, widgetname, kw=kw)
  File "/usr/lib/python3.11/tkinter/__init__.py", line 2628, in __init__
    self.tk.call(
_tkinter.TclError: image "pyimage2" doesn't exist
